[MGMenu]
#官方网站：http://www.wbini.com
#交流群号：543833245
#自定义图标文件,替换目录下的MGMenu.ico即可

#自定义桌面图标名字
DeskName=蘑菇菜单

#软件标题的名字
Title=蘑菇菜单 - 欢迎光临本网吧

#置顶应用列表
TopAPP=UPlay,Origin,Steam

#是否显示二级确认对话框 True/False
YesBox=False

#自定义游戏图标大小
IcoSize=32

#游戏菜单窗口尺寸
WinWidth=806
WinHeight=601
